### ISSUE TITLE
shorten redundant names

### ISSUE THREAD

**Issue by Qazzquimby** [FMTriguero/coding_Fall2020#3]
https://github.com/FMTriguero/coding_Fall2020/blob/95a64cb237c28f2df47dd0e8cc43f2664cc5487a/Main.py#L22

https://github.com/FMTriguero/coding_Fall2020/blob/95a64cb237c28f2df47dd0e8cc43f2664cc5487a/Main.py#L29-L30

Leads to situations like `action.action_type`

**Comment by FMTriguero** [comment]
the line 22 should be fixed, since I got ride of vector class, but the 2nd is necessary I believe no? since in "initialize" the website gives both action type and id (action type is the type of action "BREW", "CAST", "WAIT"... and action_id is the id used to cast each of the actions (one id per "BREW" action, one per "CAST" action...)
